BuildJob.sync(this, 'mobile', 'EllucianGO')
BuildJob.sync(this, 'mobile', 'MobileServer')
BuildJob.sync(this, 'mobile', 'ms-configuration-core')
BuildJob.sync(this, 'mobile', 'ms-groovy')
BuildJob.sync(this, 'mobile', 'ms-notification-core')
