import common.GlobalVars

folder('repo-sync')

class BuildJob {
  static sync(dslFactory, repofoler, reponame) {
    def foldername=repofolder.replaceALL('/', '_')
    dslFactory.folder("repo-sync/${foldername}")
    dslFactory.job("repo-sync/${foldername}/${reponame}") {
      triggers {
        cron(GlobalVars.scheduleEveryDay)
      }
      steps {
        shell(""" echo ${reponame}
          rm -rf ${reponame}
          git clone ssh://git@gitrepo.georgebrown.ca:2222/ellucian_${foldername}/${reponame}.git
          cd ${reponame}
          git remote add upstream ssh://git@source.ellucian.com/${repofolder}/${reponame}.git
          git fetch upstream
          git merge upstream/master
          git push origin master
        """)
      }
    }
  }
}

BuildJob.sync(this, 'banner/apps', 'application_navigator_app')
BuildJob.sync(this, 'banner/apps', 'banner_communication_management_ssb_app')
BuildJob.sync(this, 'banner/apps', 'banner_document_management_api_app')
BuildJob.sync(this, 'banner/apps', 'banner_employee_profile_ssb_app')
BuildJob.sync(this, 'banner/apps', 'banner_employee_ssb_app')
BuildJob.sync(this, 'banner/apps', 'banner_extensibility')
BuildJob.sync(this, 'banner/apps', 'banner_faculty_attendance_tracking_ssb_app')
BuildJob.sync(this, 'banner/apps', 'banner_finance_procurement_ssb_app')
BuildJob.sync(this, 'banner/apps', 'banner_finance_ssb_app')
BuildJob.sync(this, 'banner/apps', 'banner_general_events_app')
BuildJob.sync(this, 'banner/apps', 'banner_general_events_ssb_app')
BuildJob.sync(this, 'banner/apps', 'banner_general_ssb_app')
BuildJob.sync(this, 'banner/apps', 'banner_integration_api_app')
BuildJob.sync(this, 'banner/apps', 'banner_position_desc_ssb_app')
BuildJob.sync(this, 'banner/apps', 'banner_student_advisor_ssb_app')
BuildJob.sync(this, 'banner/apps', 'banner_student_api_app')
BuildJob.sync(this, 'banner/apps', 'banner_student_attendance_tracking_app')
BuildJob.sync(this, 'banner/apps', 'banner_student_attendance_tracking_ssb_app')
BuildJob.sync(this, 'banner/apps', 'banner_student_catalog_app')
BuildJob.sync(this, 'banner/apps', 'banner_student_etranscript_api')
BuildJob.sync(this, 'banner/apps', 'banner_student_faculty_grade_entry_app')
BuildJob.sync(this, 'banner/apps', 'banner_student_generalstudent_history_app')
BuildJob.sync(this, 'banner/apps', 'banner_student_overall_app')
BuildJob.sync(this, 'banner/apps', 'banner_student_registration_app')
BuildJob.sync(this, 'banner/apps', 'banner_student_registration_ssb_app')
BuildJob.sync(this, 'banner/apps', 'banner_student_schedule_app')
BuildJob.sync(this, 'banner/apps', 'banner_student_ssb_app')
BuildJob.sync(this, 'banner/apps', 'banner_student_success_api')
// BuildJob.sync(this, 'banner/pages', 'alumni')
// BuildJob.sync(this, 'banner/pages', 'arsys')
// BuildJob.sync(this, 'banner/pages', 'base')
// BuildJob.sync(this, 'banner/pages', 'bdr')
// BuildJob.sync(this, 'banner/pages', 'build')
// BuildJob.sync(this, 'banner/pages', 'common')
// BuildJob.sync(this, 'banner/pages', 'extsol')
// BuildJob.sync(this, 'banner/pages', 'finaid')
// BuildJob.sync(this, 'banner/pages', 'finance')
// BuildJob.sync(this, 'banner/pages', 'general')
// BuildJob.sync(this, 'banner/pages', 'payroll')
// BuildJob.sync(this, 'banner/pages', 'positioncontrol')
// BuildJob.sync(this, 'banner/pages', 'reports')
// BuildJob.sync(this, 'banner/pages', 'student')
// BuildJob.sync(this, 'banner/pages', 'studentaid')
// BuildJob.sync(this, 'banner/pages', 'workspace')
// BuildJob.sync(this, 'banner/plugins', 'banner-api')
// BuildJob.sync(this, 'banner/plugins', 'banner-restful-api-support')
// BuildJob.sync(this, 'banner/plugins', 'banner_accountsreceivable_common')
// BuildJob.sync(this, 'banner/plugins', 'banner_accountsreceivable_validation_common')
// BuildJob.sync(this, 'banner/plugins', 'banner_aurora')
// BuildJob.sync(this, 'banner/plugins', 'banner_baseline_dbupgrade')
// BuildJob.sync(this, 'banner/plugins', 'banner_codenarc')
// BuildJob.sync(this, 'banner/plugins', 'banner_common_api')
// BuildJob.sync(this, 'banner/plugins', 'banner_core')
// BuildJob.sync(this, 'banner/plugins', 'banner_db_main')
// BuildJob.sync(this, 'banner/plugins', 'banner_document_management')
// BuildJob.sync(this, 'banner/plugins', 'banner_finaid_validation')
// BuildJob.sync(this, 'banner/plugins', 'banner_finance_api')
// BuildJob.sync(this, 'banner/plugins', 'banner_finance_budget_availability')
// BuildJob.sync(this, 'banner/plugins', 'banner_finance_budget_availability_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_finance_budget_availability_validation')
// BuildJob.sync(this, 'banner/plugins', 'banner_finance_common')
// BuildJob.sync(this, 'banner/plugins', 'banner_finance_general_ledger')
// BuildJob.sync(this, 'banner/plugins', 'banner_finance_procurement')
// BuildJob.sync(this, 'banner/plugins', 'banner_finance_procurement_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_finance_validation')
// BuildJob.sync(this, 'banner/plugins', 'banner_finance_validation_common')
// BuildJob.sync(this, 'banner/plugins', 'banner_general_common')
// BuildJob.sync(this, 'banner/plugins', 'banner_general_common_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_general_common_ui_ss')
// BuildJob.sync(this, 'banner/plugins', 'banner_general_direct_deposit_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_general_events')
// BuildJob.sync(this, 'banner/plugins', 'banner_general_person')
// BuildJob.sync(this, 'banner/plugins', 'banner_general_person_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_general_personal_information_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_general_utility')
// BuildJob.sync(this, 'banner/plugins', 'banner_general_validation_common')
// BuildJob.sync(this, 'banner/plugins', 'banner_general_validation_common_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_hr_effort_reporting_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_hr_employee_profile_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_hr_labor_redistribution_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_hr_position_description_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_packaging')
// BuildJob.sync(this, 'banner/plugins', 'banner_payroll_api')
// BuildJob.sync(this, 'banner/plugins', 'banner_payroll_common')
// BuildJob.sync(this, 'banner/plugins', 'banner_posnctl_common')
// BuildJob.sync(this, 'banner/plugins', 'banner_seeddata_catalog')
// BuildJob.sync(this, 'banner/plugins', 'banner_selenium_common')
// BuildJob.sync(this, 'banner/plugins', 'banner_spring_security_cas')
// BuildJob.sync(this, 'banner/plugins', 'banner_spring_security_saml')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_admissions')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_advising_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_api')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_attendance_tracking')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_attr_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_capp')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_catalog')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_common')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_common_ss_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_common_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_faculty')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_faculty_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_generalstudent')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_history')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_recruiting')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_registration')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_schedule')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_ssb_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_student_validation')
// BuildJob.sync(this, 'banner/plugins', 'banner_ui')
// BuildJob.sync(this, 'banner/plugins', 'banner_ui_ss')
// BuildJob.sync(this, 'banner/plugins', 'banner_xe_dbupgrade')
// BuildJob.sync(this, 'banner/plugins', 'domain_extension')
// BuildJob.sync(this, 'banner/plugins', 'grails-constraints')
// BuildJob.sync(this, 'banner/plugins', 'i18n_core')
// BuildJob.sync(this, 'banner/plugins', 'restful-api')
// BuildJob.sync(this, 'banner/plugins', 'seamless')
// BuildJob.sync(this, 'banner/plugins', 'sghe_aurora')
// BuildJob.sync(this, 'banner/plugins', 'sghe_zk_core')
// BuildJob.sync(this, 'banner/plugins', 'spring_security_cas')
// BuildJob.sync(this, 'banner/plugins', 'spring_security_saml')
// BuildJob.sync(this, 'banner/plugins', 'web-app-extensibility')
// BuildJob.sync(this, 'banner/plugins', 'webify')
// BuildJob.sync(this, 'framework/plugins','banner-sspb')
// BuildJob.sync(this, 'framework/plugins','seamless')
// BuildJob.sync(this, 'framework/plugins','webify')
// BuildJob.sync(this, 'mobile', 'EllucianGO')
// BuildJob.sync(this, 'mobile', 'MobileServer')
// BuildJob.sync(this, 'mobile', 'ms-configuration-core')
// BuildJob.sync(this, 'mobile', 'ms-groovy')
// BuildJob.sync(this, 'mobile', 'ms-notification-core')
