import common.BuildJob

BuildJob.sync(this, 'banner/pages', 'alumni')
BuildJob.sync(this, 'banner/pages', 'arsys')
BuildJob.sync(this, 'banner/pages', 'base')
BuildJob.sync(this, 'banner/pages', 'bdr')
BuildJob.sync(this, 'banner/pages', 'build')
BuildJob.sync(this, 'banner/pages', 'common')
BuildJob.sync(this, 'banner/pages', 'extsol')
BuildJob.sync(this, 'banner/pages', 'finaid')
BuildJob.sync(this, 'banner/pages', 'finance')
BuildJob.sync(this, 'banner/pages', 'general')
BuildJob.sync(this, 'banner/pages', 'payroll')
BuildJob.sync(this, 'banner/pages', 'positioncontrol')
BuildJob.sync(this, 'banner/pages', 'reports')
BuildJob.sync(this, 'banner/pages', 'student')
BuildJob.sync(this, 'banner/pages', 'studentaid')
BuildJob.sync(this, 'banner/pages', 'workspace')
